package se.cloudshop.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

@Component
@Order(0)
public class DatabaseSchemaPatch implements CommandLineRunner {

  private static final Logger log = LoggerFactory.getLogger(DatabaseSchemaPatch.class);

  private final JdbcTemplate jdbcTemplate;
  private final boolean schemaPatchEnabled;

  public DatabaseSchemaPatch(
      JdbcTemplate jdbcTemplate,
      @Value("${app.schema-patch.enabled:true}") boolean schemaPatchEnabled) {
    this.jdbcTemplate = jdbcTemplate;
    this.schemaPatchEnabled = schemaPatchEnabled;
  }

  @Override
  public void run(String... args) {
    if (!schemaPatchEnabled) {
      log.info("Database schema patch is disabled by app.schema-patch.enabled=false.");
      return;
    }

    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS currencies (currency_code varchar(3) PRIMARY KEY, minor_unit_exponent integer NOT NULL CHECK (minor_unit_exponent BETWEEN 0 AND 9))");
    jdbcTemplate.execute("INSERT INTO currencies (currency_code, minor_unit_exponent) VALUES ('SEK', 2), ('JPY', 0), ('KWD', 3), ('TND', 3) ON CONFLICT (currency_code) DO NOTHING");

    jdbcTemplate.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS active boolean DEFAULT true");
    jdbcTemplate.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS discount_price integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS vat_percent integer DEFAULT 25");
    jdbcTemplate.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS discount_label varchar(255)");
    jdbcTemplate.execute("UPDATE products SET active = true WHERE active IS NULL");
    jdbcTemplate.execute("UPDATE products SET discount_price = 0 WHERE discount_price IS NULL");
    // Shadow columns for the versioned minor-unit migration. Legacy whole-SEK
    // columns remain authoritative until every read/write path is migrated.
    jdbcTemplate.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS price_minor bigint");
    jdbcTemplate.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS discount_price_minor bigint");
    jdbcTemplate.execute("ALTER TABLE products ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE products SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("UPDATE products SET price_minor = CAST(ROUND(CAST(price AS numeric) * 100, 0) AS bigint) WHERE price_minor IS NULL AND price IS NOT NULL");
    jdbcTemplate.execute("UPDATE products SET discount_price_minor = CAST(ROUND(CAST(discount_price AS numeric) * 100, 0) AS bigint) WHERE discount_price_minor IS NULL AND discount_price IS NOT NULL");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS net_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS vat_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS vat_percent integer DEFAULT 25");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS total_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS quantity integer DEFAULT 1");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS ordinary_price integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS discount_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS discount_label varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS status varchar(255) DEFAULT 'DRAFT'");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS stripe_checkout_session_id varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS invoice_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS invoice_date date DEFAULT CURRENT_DATE");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS due_date date");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS payment_terms_days integer DEFAULT 30");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS f_tax_approved boolean DEFAULT true");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS ocr_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS plus_giro varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS payment_recipient varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS paid_date date");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS paid_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS payment_reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS refund_date date");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS refunded_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS refund_reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS reminder_sent_date date");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS credit_invoice boolean DEFAULT false");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS credited_invoice_id bigint");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS ordinary_price_minor bigint");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS discount_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS net_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS vat_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS total_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS paid_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS refunded_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE customer_orders SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("UPDATE customer_orders SET ordinary_price_minor = CAST(ROUND(CAST(ordinary_price AS numeric) * 100, 0) AS bigint) WHERE ordinary_price_minor IS NULL AND ordinary_price IS NOT NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET discount_amount_minor = CAST(ROUND(CAST(discount_amount AS numeric) * 100, 0) AS bigint) WHERE discount_amount_minor IS NULL AND discount_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET net_amount_minor = CAST(ROUND(CAST(net_amount AS numeric) * 100, 0) AS bigint) WHERE net_amount_minor IS NULL AND net_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET vat_amount_minor = CAST(ROUND(CAST(vat_amount AS numeric) * 100, 0) AS bigint) WHERE vat_amount_minor IS NULL AND vat_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET total_amount_minor = CAST(ROUND(CAST(total_amount AS numeric) * 100, 0) AS bigint) WHERE total_amount_minor IS NULL AND total_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET paid_amount_minor = CAST(ROUND(CAST(paid_amount AS numeric) * 100, 0) AS bigint) WHERE paid_amount_minor IS NULL AND paid_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET refunded_amount_minor = CAST(ROUND(CAST(refunded_amount AS numeric) * 100, 0) AS bigint) WHERE refunded_amount_minor IS NULL AND refunded_amount IS NOT NULL");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS customer_orders_invoice_number_idx ON customer_orders(invoice_number) WHERE invoice_number IS NOT NULL AND invoice_number <> ''");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS customer_orders_ocr_number_idx ON customer_orders(ocr_number) WHERE ocr_number IS NOT NULL AND ocr_number <> ''");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS invoice_payments (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE invoice_payments ADD COLUMN IF NOT EXISTS invoice_id bigint");
    jdbcTemplate.execute("ALTER TABLE invoice_payments ADD COLUMN IF NOT EXISTS payment_date date");
    jdbcTemplate.execute("ALTER TABLE invoice_payments ADD COLUMN IF NOT EXISTS amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE invoice_payments ADD COLUMN IF NOT EXISTS reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE invoice_payments ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE invoice_payments ADD COLUMN IF NOT EXISTS amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE invoice_payments ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE invoice_payments SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("UPDATE invoice_payments SET amount_minor = CAST(ROUND(CAST(amount AS numeric) * 100, 0) AS bigint) WHERE amount_minor IS NULL AND amount IS NOT NULL");
    jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS invoice_payments_identity_unique ON invoice_payments (invoice_id, payment_date, amount, lower(reference)) WHERE reference IS NOT NULL AND reference <> ''");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS money_migration_ledger (migration_key varchar(128) PRIMARY KEY, source_unit varchar(32) NOT NULL, target_unit varchar(32) NOT NULL, applied_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP)");
    jdbcTemplate.execute("INSERT INTO money_migration_ledger (migration_key, source_unit, target_unit) VALUES ('core-invoice-shadow-v1', 'whole-krona', 'minor-unit') ON CONFLICT (migration_key) DO NOTHING");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS invoice_reminders (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE invoice_reminders ADD COLUMN IF NOT EXISTS invoice_id bigint");
    jdbcTemplate.execute("ALTER TABLE invoice_reminders ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE invoice_reminders ADD COLUMN IF NOT EXISTS method varchar(255)");
    jdbcTemplate.execute("ALTER TABLE invoice_reminders ADD COLUMN IF NOT EXISTS status varchar(255)");
    jdbcTemplate.execute("ALTER TABLE invoice_reminders ADD COLUMN IF NOT EXISTS recipient_email varchar(255)");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS stripe_webhook_events (event_id varchar(255) PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE stripe_webhook_events ADD COLUMN IF NOT EXISTS event_type varchar(255)");
    jdbcTemplate.execute("ALTER TABLE stripe_webhook_events ADD COLUMN IF NOT EXISTS processed_at timestamp");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS stripe_payouts (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS payout_date date");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS gross_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS fee_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS net_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS gross_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS fee_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS net_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS voucher_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE stripe_payouts ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE stripe_payouts SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS stripe_payouts_reference_unique ON stripe_payouts(reference) WHERE reference IS NOT NULL AND reference <> ''");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS bank_reconciliation_entries (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS bank_row_id varchar(255)");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS bank_date date");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS description varchar(255)");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS entry_type varchar(255)");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS status varchar(255)");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS match_label varchar(255)");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS booked_at timestamp");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE bank_reconciliation_entries SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS bank_reconciliation_entries_bank_row_id_idx ON bank_reconciliation_entries(bank_row_id)");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS vat_filings (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS period_from date");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS period_to date");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS output_vat integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS input_vat integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS vat_to_pay integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS output_vat_minor bigint");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS input_vat_minor bigint");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS vat_to_pay_minor bigint");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS status varchar(255)");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS submission_reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS payment_reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS note varchar(1000)");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS submitted_at timestamp");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS paid_at timestamp");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS updated_at timestamp");
    jdbcTemplate.execute("ALTER TABLE vat_filings ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE vat_filings SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS vat_filings_period_unique ON vat_filings(period_from, period_to)");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS audit_events (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS event_type varchar(255)");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS entity_type varchar(255)");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS entity_id varchar(255)");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS event_action varchar(255)");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS message varchar(1000)");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE audit_events SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS actor_email varchar(255)");
    jdbcTemplate.execute("ALTER TABLE audit_events ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS audit_events_created_at_idx ON audit_events(created_at)");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS audit_events_entity_idx ON audit_events(entity_type, entity_id)");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS payroll_snapshots (id bigint PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE payroll_snapshots ADD COLUMN IF NOT EXISTS content text");
    jdbcTemplate.execute("ALTER TABLE payroll_snapshots ADD COLUMN IF NOT EXISTS updated_at timestamp");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS payroll_snapshot_revisions (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE payroll_snapshot_revisions ADD COLUMN IF NOT EXISTS content text");
    jdbcTemplate.execute("ALTER TABLE payroll_snapshot_revisions ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE customers ADD COLUMN IF NOT EXISTS personal_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customers ADD COLUMN IF NOT EXISTS address varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customers ADD COLUMN IF NOT EXISTS phone varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customers ADD COLUMN IF NOT EXISTS postal_code varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customers ADD COLUMN IF NOT EXISTS city varchar(255)");
    jdbcTemplate.execute("ALTER TABLE customers ADD COLUMN IF NOT EXISTS archived boolean DEFAULT false");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS expenses (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS expense_date date");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS description varchar(255)");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS net_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS vat_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS total_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS net_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS vat_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS total_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS category varchar(255)");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS paid_from varchar(255)");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_file_name varchar(255)");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_content_type varchar(255)");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_storage_path varchar(1000)");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_sha256 varchar(64)");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS receipt_uploaded_at timestamp");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE expenses ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE expenses SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS card_purchases (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS purchase_date date");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS merchant_name varchar(255)");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS card_holder varchar(255)");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS card_last4 varchar(16)");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS net_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS vat_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS total_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS net_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS vat_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS total_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS category varchar(255)");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS clearing_account varchar(255)");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS status varchar(64) DEFAULT 'review'");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS booked_expense_id bigint");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS updated_at timestamp");
    jdbcTemplate.execute("ALTER TABLE card_purchases ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE card_purchases SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS card_purchases_purchase_date_idx ON card_purchases(purchase_date)");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS suppliers (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS name varchar(255)");
    jdbcTemplate.execute("ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS email varchar(255)");
    jdbcTemplate.execute("ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS org_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS phone varchar(255)");
    jdbcTemplate.execute("ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS payment_info varchar(512)");
    jdbcTemplate.execute("ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS archived boolean DEFAULT false");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS suppliers_name_idx ON suppliers(name)");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS supplier_invoices (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS supplier_id bigint");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS supplier_name varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS supplier_email varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS supplier_org_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS invoice_date date");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS due_date date");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS description varchar(512)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS total_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS vat_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS net_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS total_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS vat_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS net_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS category varchar(64)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS status varchar(64) DEFAULT 'unpaid'");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS paid_at date");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS paid_amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS paid_amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS payment_reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS payment_history text");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS cancelled_at date");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS cancellation_voucher_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS self_billing boolean DEFAULT false");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS buyer_name varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS buyer_reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS approval_reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE supplier_invoices ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE supplier_invoices SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS supplier_invoices_supplier_id_idx ON supplier_invoices(supplier_id)");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS supplier_invoices_due_date_idx ON supplier_invoices(due_date)");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS supplier_invoice_payments (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoice_payments ADD COLUMN IF NOT EXISTS supplier_invoice_id bigint");
    jdbcTemplate.execute("ALTER TABLE supplier_invoice_payments ADD COLUMN IF NOT EXISTS payment_date date");
    jdbcTemplate.execute("ALTER TABLE supplier_invoice_payments ADD COLUMN IF NOT EXISTS amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE supplier_invoice_payments ADD COLUMN IF NOT EXISTS amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE supplier_invoice_payments ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("ALTER TABLE supplier_invoice_payments ADD COLUMN IF NOT EXISTS reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE supplier_invoice_payments ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("UPDATE supplier_invoice_payments SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("UPDATE supplier_invoice_payments SET amount_minor = CAST(ROUND(CAST(amount AS numeric) * 100, 0) AS bigint) WHERE amount_minor IS NULL AND amount IS NOT NULL");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS supplier_invoice_payments_invoice_date_idx ON supplier_invoice_payments(supplier_invoice_id, payment_date, id)");
    jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS supplier_invoice_payments_identity_unique ON supplier_invoice_payments (supplier_invoice_id, payment_date, amount, lower(reference)) WHERE reference IS NOT NULL AND reference <> ''");
    jdbcTemplate.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_supplier_invoice_payments_invoice' AND conrelid = 'supplier_invoice_payments'::regclass) THEN ALTER TABLE supplier_invoice_payments ADD CONSTRAINT fk_supplier_invoice_payments_invoice FOREIGN KEY (supplier_invoice_id) REFERENCES supplier_invoices(id); END IF; END $$");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS recurring_contracts (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS customer_id bigint");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS customer_name varchar(255)");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS service_id bigint");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS service_name varchar(255)");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS quantity integer DEFAULT 1");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS contract_interval varchar(255)");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS next_invoice_date date");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS active boolean DEFAULT true");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS archived boolean DEFAULT false");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS last_invoice_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE recurring_contracts ADD COLUMN IF NOT EXISTS archived_at timestamp");
    jdbcTemplate.execute("ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS voucher_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS voucher_date date DEFAULT CURRENT_DATE");
    jdbcTemplate.execute("ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS correction_of_voucher_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS expense_id bigint");
    jdbcTemplate.execute("ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS supplier_invoice_id bigint");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS journal_entries_voucher_number_idx ON journal_entries(voucher_number) WHERE voucher_number IS NOT NULL AND voucher_number <> ''");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS journal_entries_expense_id_idx ON journal_entries(expense_id) WHERE expense_id IS NOT NULL");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS journal_entries_supplier_invoice_id_idx ON journal_entries(supplier_invoice_id) WHERE supplier_invoice_id IS NOT NULL");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS voucher_approvals (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE voucher_approvals ADD COLUMN IF NOT EXISTS voucher_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE voucher_approvals ADD COLUMN IF NOT EXISTS status varchar(255)");
    jdbcTemplate.execute("ALTER TABLE voucher_approvals ADD COLUMN IF NOT EXISTS note text");
    jdbcTemplate.execute("ALTER TABLE voucher_approvals ALTER COLUMN note TYPE text");
    jdbcTemplate.execute("ALTER TABLE voucher_approvals ADD COLUMN IF NOT EXISTS reviewer varchar(255)");
    jdbcTemplate.execute("ALTER TABLE voucher_approvals ADD COLUMN IF NOT EXISTS reviewed_at timestamp");
    jdbcTemplate.execute("ALTER TABLE voucher_approvals ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE voucher_approvals ADD COLUMN IF NOT EXISTS updated_at timestamp");
    jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS voucher_approvals_voucher_number_unique ON voucher_approvals(voucher_number) WHERE voucher_number IS NOT NULL AND voucher_number <> ''");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS voucher_approvals_reviewed_at_idx ON voucher_approvals(reviewed_at)");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS owner_transactions (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS transaction_type varchar(64)");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS transaction_date date");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS amount integer DEFAULT 0");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS amount_minor bigint");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE owner_transactions SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS description varchar(512)");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS reference varchar(255)");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS debit_account varchar(64)");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS credit_account varchar(64)");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS status varchar(64) DEFAULT 'draft'");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS voucher_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS created_at timestamp");
    jdbcTemplate.execute("ALTER TABLE owner_transactions ADD COLUMN IF NOT EXISTS updated_at timestamp");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS owner_transactions_date_idx ON owner_transactions(transaction_date)");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS app_settings (id bigint PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS company_name varchar(255)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS company_address varchar(1000)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS company_postal_code varchar(255)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS company_city varchar(255)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS company_organization_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS vat_registration_number varchar(255)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS contact_email varchar(255)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS plus_giro varchar(255)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS default_ocr varchar(255)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS payment_recipient varchar(255)");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS company_type varchar(255) DEFAULT 'SOLE_TRADER'");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS accounting_method varchar(255) DEFAULT 'INVOICE_METHOD'");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS vat_reporting_period varchar(255) DEFAULT 'QUARTERLY'");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS fiscal_year_start_month integer DEFAULT 1");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS fiscal_year_end_month integer DEFAULT 12");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS vat_percent integer DEFAULT 25");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS payment_terms_days integer DEFAULT 30");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS f_tax_approved boolean DEFAULT true");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS invoice_email_template text");
    jdbcTemplate.execute("ALTER TABLE app_settings ALTER COLUMN invoice_email_template TYPE text");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS automatic_invoice_reminders_enabled boolean DEFAULT true");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS invoice_reminder_days_before_due integer DEFAULT 5");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS invoice_reminder_template text");
    jdbcTemplate.execute("ALTER TABLE app_settings ALTER COLUMN invoice_reminder_template TYPE text");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS overdue_invoice_reminders_enabled boolean DEFAULT true");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS overdue_invoice_reminder_days_after_due integer DEFAULT 3");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS overdue_invoice_reminder_template text");
    jdbcTemplate.execute("ALTER TABLE app_settings ALTER COLUMN overdue_invoice_reminder_template TYPE text");
    jdbcTemplate.execute("ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS accounting_locked_through_date date");
    jdbcTemplate.execute("UPDATE customer_orders SET status = 'DRAFT' WHERE status IS NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET quantity = 1 WHERE quantity IS NULL OR quantity = 0");
    jdbcTemplate.execute("UPDATE customer_orders SET ordinary_price = net_amount WHERE ordinary_price IS NULL OR ordinary_price = 0");
    jdbcTemplate.execute("UPDATE customer_orders SET discount_amount = 0 WHERE discount_amount IS NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET invoice_date = CURRENT_DATE WHERE invoice_date IS NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET payment_terms_days = 30 WHERE payment_terms_days IS NULL OR payment_terms_days = 0");
    jdbcTemplate.execute("UPDATE customer_orders SET due_date = invoice_date + payment_terms_days WHERE due_date IS NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET f_tax_approved = true WHERE f_tax_approved IS NULL");
    jdbcTemplate.execute("UPDATE customer_orders SET refunded_amount = 0 WHERE refunded_amount IS NULL");
    jdbcTemplate.execute("UPDATE customers SET archived = false WHERE archived IS NULL");
    jdbcTemplate.execute("UPDATE suppliers SET archived = false WHERE archived IS NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET status = 'unpaid' WHERE status IS NULL OR status = ''");
    jdbcTemplate.execute("UPDATE supplier_invoices SET net_amount = GREATEST(total_amount - vat_amount, 0) WHERE net_amount IS NULL OR net_amount = 0");
    jdbcTemplate.execute("UPDATE supplier_invoices SET paid_amount = 0 WHERE paid_amount IS NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET paid_amount = total_amount WHERE (status = 'paid' OR paid_at IS NOT NULL) AND paid_amount = 0");
    jdbcTemplate.execute("UPDATE supplier_invoices SET total_amount_minor = CAST(ROUND(CAST(total_amount AS numeric) * 100, 0) AS bigint) WHERE total_amount_minor IS NULL AND total_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET vat_amount_minor = CAST(ROUND(CAST(vat_amount AS numeric) * 100, 0) AS bigint) WHERE vat_amount_minor IS NULL AND vat_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET net_amount_minor = CAST(ROUND(CAST(net_amount AS numeric) * 100, 0) AS bigint) WHERE net_amount_minor IS NULL AND net_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET paid_amount_minor = CAST(ROUND(CAST(paid_amount AS numeric) * 100, 0) AS bigint) WHERE paid_amount_minor IS NULL AND paid_amount IS NOT NULL");
    jdbcTemplate.execute("INSERT INTO money_migration_ledger (migration_key, source_unit, target_unit) VALUES ('supplier-invoice-shadow-v1', 'whole-krona', 'minor-unit') ON CONFLICT (migration_key) DO NOTHING");
    jdbcTemplate.execute("UPDATE supplier_invoices SET payment_reference = '' WHERE payment_reference IS NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET payment_history = '' WHERE payment_history IS NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET self_billing = false WHERE self_billing IS NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET buyer_name = '' WHERE buyer_name IS NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET buyer_reference = '' WHERE buyer_reference IS NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET approval_reference = '' WHERE approval_reference IS NULL");
    jdbcTemplate.execute("UPDATE supplier_invoices SET status = 'cancelled' WHERE cancellation_voucher_number IS NOT NULL AND cancellation_voucher_number <> ''");
    jdbcTemplate.execute("UPDATE expenses SET net_amount_minor = CAST(ROUND(CAST(net_amount AS numeric) * 100, 0) AS bigint) WHERE net_amount_minor IS NULL AND net_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE expenses SET vat_amount_minor = CAST(ROUND(CAST(vat_amount AS numeric) * 100, 0) AS bigint) WHERE vat_amount_minor IS NULL AND vat_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE expenses SET total_amount_minor = CAST(ROUND(CAST(total_amount AS numeric) * 100, 0) AS bigint) WHERE total_amount_minor IS NULL AND total_amount IS NOT NULL");
    jdbcTemplate.execute("INSERT INTO money_migration_ledger (migration_key, source_unit, target_unit) VALUES ('expense-shadow-v1', 'whole-krona', 'minor-unit') ON CONFLICT (migration_key) DO NOTHING");
    jdbcTemplate.execute("UPDATE stripe_payouts SET gross_amount_minor = CAST(ROUND(CAST(gross_amount AS numeric) * 100, 0) AS bigint) WHERE gross_amount_minor IS NULL AND gross_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE stripe_payouts SET fee_amount_minor = CAST(ROUND(CAST(fee_amount AS numeric) * 100, 0) AS bigint) WHERE fee_amount_minor IS NULL AND fee_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE stripe_payouts SET net_amount_minor = CAST(ROUND(CAST(net_amount AS numeric) * 100, 0) AS bigint) WHERE net_amount_minor IS NULL AND net_amount IS NOT NULL");
    jdbcTemplate.execute("INSERT INTO money_migration_ledger (migration_key, source_unit, target_unit) VALUES ('stripe-payout-shadow-v1', 'whole-krona', 'minor-unit') ON CONFLICT (migration_key) DO NOTHING");
    jdbcTemplate.execute("UPDATE vat_filings SET output_vat_minor = CAST(ROUND(CAST(output_vat AS numeric) * 100, 0) AS bigint) WHERE output_vat_minor IS NULL AND output_vat IS NOT NULL");
    jdbcTemplate.execute("UPDATE vat_filings SET input_vat_minor = CAST(ROUND(CAST(input_vat AS numeric) * 100, 0) AS bigint) WHERE input_vat_minor IS NULL AND input_vat IS NOT NULL");
    jdbcTemplate.execute("UPDATE vat_filings SET vat_to_pay_minor = CAST(ROUND(CAST(vat_to_pay AS numeric) * 100, 0) AS bigint) WHERE vat_to_pay_minor IS NULL AND vat_to_pay IS NOT NULL");
    jdbcTemplate.execute("INSERT INTO money_migration_ledger (migration_key, source_unit, target_unit) VALUES ('vat-filing-shadow-v1', 'whole-krona', 'minor-unit') ON CONFLICT (migration_key) DO NOTHING");
    jdbcTemplate.execute("UPDATE card_purchases SET net_amount_minor = CAST(ROUND(CAST(net_amount AS numeric) * 100, 0) AS bigint) WHERE net_amount_minor IS NULL AND net_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE card_purchases SET vat_amount_minor = CAST(ROUND(CAST(vat_amount AS numeric) * 100, 0) AS bigint) WHERE vat_amount_minor IS NULL AND vat_amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE card_purchases SET total_amount_minor = CAST(ROUND(CAST(total_amount AS numeric) * 100, 0) AS bigint) WHERE total_amount_minor IS NULL AND total_amount IS NOT NULL");
    jdbcTemplate.execute("INSERT INTO money_migration_ledger (migration_key, source_unit, target_unit) VALUES ('card-purchase-shadow-v1', 'whole-krona', 'minor-unit') ON CONFLICT (migration_key) DO NOTHING");
    jdbcTemplate.execute("UPDATE bank_reconciliation_entries SET amount_minor = CAST(ROUND(CAST(amount AS numeric) * 100, 0) AS bigint) WHERE amount_minor IS NULL AND amount IS NOT NULL");
    jdbcTemplate.execute("INSERT INTO money_migration_ledger (migration_key, source_unit, target_unit) VALUES ('bank-reconciliation-shadow-v1', 'whole-krona', 'minor-unit') ON CONFLICT (migration_key) DO NOTHING");
    jdbcTemplate.execute("UPDATE recurring_contracts SET quantity = 1 WHERE quantity IS NULL OR quantity = 0");
    jdbcTemplate.execute("UPDATE recurring_contracts SET contract_interval = 'monthly' WHERE contract_interval IS NULL OR contract_interval = ''");
    jdbcTemplate.execute("UPDATE recurring_contracts SET next_invoice_date = CURRENT_DATE WHERE next_invoice_date IS NULL");
    jdbcTemplate.execute("UPDATE recurring_contracts SET active = true WHERE active IS NULL");
    jdbcTemplate.execute("UPDATE recurring_contracts SET archived = false WHERE archived IS NULL");
    jdbcTemplate.execute("UPDATE owner_transactions SET status = 'draft' WHERE status IS NULL OR status = ''");
    jdbcTemplate.execute("UPDATE owner_transactions SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL");
    jdbcTemplate.execute("UPDATE owner_transactions SET updated_at = created_at WHERE updated_at IS NULL");
    jdbcTemplate.execute("UPDATE owner_transactions SET status = 'booked' WHERE voucher_number IS NOT NULL AND voucher_number <> ''");
    jdbcTemplate.execute("UPDATE app_settings SET company_type = 'SOLE_TRADER' WHERE company_type IS NULL");
    jdbcTemplate.execute("UPDATE app_settings SET accounting_method = 'INVOICE_METHOD' WHERE accounting_method IS NULL OR accounting_method = ''");
    jdbcTemplate.execute("UPDATE app_settings SET vat_reporting_period = 'QUARTERLY' WHERE vat_reporting_period IS NULL OR vat_reporting_period = ''");
    jdbcTemplate.execute("UPDATE app_settings SET fiscal_year_start_month = 1 WHERE fiscal_year_start_month IS NULL OR fiscal_year_start_month < 1 OR fiscal_year_start_month > 12");
    jdbcTemplate.execute("UPDATE app_settings SET fiscal_year_end_month = 12 WHERE fiscal_year_end_month IS NULL OR fiscal_year_end_month < 1 OR fiscal_year_end_month > 12");
    jdbcTemplate.execute("UPDATE app_settings SET automatic_invoice_reminders_enabled = true WHERE automatic_invoice_reminders_enabled IS NULL");
    jdbcTemplate.execute("UPDATE app_settings SET invoice_email_template = 'Hej {kundnamn},\n\nBifogat finns faktura {fakturanummer}.\nForfallodatum: {forfallodatum}.\nAtt betala: {belopp} SEK.\n\nBetalning kan goras till PlusGiro {plusgiro} med OCR {ocr}.\nBetalningsmottagare: {betalningsmottagare}.\n\nVanliga halsningar,\n{foretag}\n{kontaktEpost}' WHERE invoice_email_template IS NULL OR invoice_email_template = ''");
    jdbcTemplate.execute("UPDATE app_settings SET invoice_reminder_days_before_due = 5 WHERE invoice_reminder_days_before_due IS NULL OR invoice_reminder_days_before_due = 0");
    jdbcTemplate.execute("UPDATE app_settings SET invoice_reminder_template = 'Hej {kundnamn},\n\nVi vill paminna om faktura {fakturanummer}.\nForfallodatum: {forfallodatum}.\nKvar att betala: {belopp} SEK.\n\nBetalning kan goras till PlusGiro {plusgiro} med OCR {ocr}.\nBetalningsmottagare: {betalningsmottagare}.\n\nVanliga halsningar,\n{foretag}\n{kontaktEpost}' WHERE invoice_reminder_template IS NULL OR invoice_reminder_template = ''");
    jdbcTemplate.execute("UPDATE app_settings SET overdue_invoice_reminders_enabled = true WHERE overdue_invoice_reminders_enabled IS NULL");
    jdbcTemplate.execute("UPDATE app_settings SET overdue_invoice_reminder_days_after_due = 3 WHERE overdue_invoice_reminder_days_after_due IS NULL OR overdue_invoice_reminder_days_after_due = 0");
    jdbcTemplate.execute("ALTER TABLE accounts ADD COLUMN IF NOT EXISTS company_type varchar(255) DEFAULT 'BOTH'");
    jdbcTemplate.execute("UPDATE accounts SET company_type = 'BOTH' WHERE company_type IS NULL");
    jdbcTemplate.execute("UPDATE journal_entries SET voucher_date = CURRENT_DATE WHERE voucher_date IS NULL");
    jdbcTemplate.execute("ALTER TABLE bank_reconciliation_entries ADD COLUMN IF NOT EXISTS journal_entry_id bigint");
    jdbcTemplate.execute("ALTER TABLE customer_orders ADD COLUMN IF NOT EXISTS document_snapshot text");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS invoice_originals (invoice_id bigint PRIMARY KEY REFERENCES customer_orders(id), pdf bytea NOT NULL, sha256 varchar(64) NOT NULL, archived_at timestamp with time zone NOT NULL)");
    jdbcTemplate.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_invoice_originals_invoice') THEN ALTER TABLE invoice_originals ADD CONSTRAINT fk_invoice_originals_invoice FOREIGN KEY (invoice_id) REFERENCES customer_orders(id); END IF; END $$");
    jdbcTemplate.execute("CREATE TABLE IF NOT EXISTS email_delivery_attempts (id bigserial PRIMARY KEY)");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS delivery_type varchar(64) NOT NULL DEFAULT 'INVOICE_EMAIL'");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS invoice_id bigint");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS recipient_email varchar(255) NOT NULL DEFAULT ''");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS subject varchar(512) NOT NULL DEFAULT ''");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS body text NOT NULL DEFAULT ''");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS attachment_name varchar(255)");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS attachment_content bytea");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS attachment_sha256 varchar(64)");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS status varchar(32) NOT NULL DEFAULT 'PENDING'");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS attempts integer NOT NULL DEFAULT 1");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS last_error varchar(2000)");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP");
    jdbcTemplate.execute("ALTER TABLE email_delivery_attempts ADD COLUMN IF NOT EXISTS sent_at timestamp with time zone");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS email_delivery_attempts_status_idx ON email_delivery_attempts(status, updated_at)");
    jdbcTemplate.execute("CREATE INDEX IF NOT EXISTS email_delivery_attempts_invoice_idx ON email_delivery_attempts(invoice_id, created_at)");
    jdbcTemplate.execute("CREATE UNIQUE INDEX IF NOT EXISTS uk_bank_reconciliation_journal ON bank_reconciliation_entries (journal_entry_id)");
    jdbcTemplate.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_bank_reconciliation_journal' AND conrelid = 'bank_reconciliation_entries'::regclass) THEN ALTER TABLE bank_reconciliation_entries ADD CONSTRAINT fk_bank_reconciliation_journal FOREIGN KEY (journal_entry_id) REFERENCES journal_entries(id); END IF; END $$");
    jdbcTemplate.execute("ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS debit_minor bigint");
    jdbcTemplate.execute("ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS credit_minor bigint");
    jdbcTemplate.execute("ALTER TABLE journal_entries ADD COLUMN IF NOT EXISTS currency_code varchar(3) DEFAULT 'SEK'");
    jdbcTemplate.execute("UPDATE journal_entries SET currency_code = 'SEK' WHERE currency_code IS NULL OR currency_code = ''");
    jdbcTemplate.execute("UPDATE journal_entries SET debit_minor = CAST(ROUND(CAST(debit AS numeric) * 100, 0) AS bigint) WHERE debit_minor IS NULL AND debit IS NOT NULL");
    jdbcTemplate.execute("UPDATE journal_entries SET credit_minor = CAST(ROUND(CAST(credit AS numeric) * 100, 0) AS bigint) WHERE credit_minor IS NULL AND credit IS NOT NULL");
    jdbcTemplate.execute("UPDATE owner_transactions SET amount_minor = CAST(ROUND(CAST(amount AS numeric) * 100, 0) AS bigint) WHERE amount_minor IS NULL AND amount IS NOT NULL");
    jdbcTemplate.execute("UPDATE audit_events SET amount_minor = CAST(ROUND(CAST(amount AS numeric) * 100, 0) AS bigint) WHERE amount_minor IS NULL AND amount IS NOT NULL");
    jdbcTemplate.execute("INSERT INTO money_migration_ledger (migration_key, source_unit, target_unit) VALUES ('journal-entry-shadow-v1', 'whole-krona', 'minor-unit') ON CONFLICT (migration_key) DO NOTHING");
    jdbcTemplate.execute("CREATE OR REPLACE FUNCTION sync_money_shadow_fields() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF TG_TABLE_NAME = 'products' THEN NEW.price_minor = CASE WHEN NEW.price IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.price AS numeric) * 100, 0) AS bigint) END; NEW.discount_price_minor = CASE WHEN NEW.discount_price IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.discount_price AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'customer_orders' THEN NEW.ordinary_price_minor = CASE WHEN NEW.ordinary_price IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.ordinary_price AS numeric) * 100, 0) AS bigint) END; NEW.discount_amount_minor = CASE WHEN NEW.discount_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.discount_amount AS numeric) * 100, 0) AS bigint) END; NEW.net_amount_minor = CASE WHEN NEW.net_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.net_amount AS numeric) * 100, 0) AS bigint) END; NEW.vat_amount_minor = CASE WHEN NEW.vat_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.vat_amount AS numeric) * 100, 0) AS bigint) END; NEW.total_amount_minor = CASE WHEN NEW.total_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.total_amount AS numeric) * 100, 0) AS bigint) END; NEW.paid_amount_minor = CASE WHEN NEW.paid_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.paid_amount AS numeric) * 100, 0) AS bigint) END; NEW.refunded_amount_minor = CASE WHEN NEW.refunded_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.refunded_amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'invoice_payments' THEN NEW.amount_minor = CASE WHEN NEW.amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'supplier_invoices' THEN NEW.total_amount_minor = CASE WHEN NEW.total_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.total_amount AS numeric) * 100, 0) AS bigint) END; NEW.vat_amount_minor = CASE WHEN NEW.vat_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.vat_amount AS numeric) * 100, 0) AS bigint) END; NEW.net_amount_minor = CASE WHEN NEW.net_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.net_amount AS numeric) * 100, 0) AS bigint) END; NEW.paid_amount_minor = CASE WHEN NEW.paid_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.paid_amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'expenses' THEN NEW.net_amount_minor = CASE WHEN NEW.net_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.net_amount AS numeric) * 100, 0) AS bigint) END; NEW.vat_amount_minor = CASE WHEN NEW.vat_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.vat_amount AS numeric) * 100, 0) AS bigint) END; NEW.total_amount_minor = CASE WHEN NEW.total_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.total_amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'card_purchases' THEN NEW.net_amount_minor = CASE WHEN NEW.net_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.net_amount AS numeric) * 100, 0) AS bigint) END; NEW.vat_amount_minor = CASE WHEN NEW.vat_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.vat_amount AS numeric) * 100, 0) AS bigint) END; NEW.total_amount_minor = CASE WHEN NEW.total_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.total_amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'stripe_payouts' THEN NEW.gross_amount_minor = CASE WHEN NEW.gross_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.gross_amount AS numeric) * 100, 0) AS bigint) END; NEW.fee_amount_minor = CASE WHEN NEW.fee_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.fee_amount AS numeric) * 100, 0) AS bigint) END; NEW.net_amount_minor = CASE WHEN NEW.net_amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.net_amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'bank_reconciliation_entries' THEN NEW.amount_minor = CASE WHEN NEW.amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'vat_filings' THEN NEW.output_vat_minor = CASE WHEN NEW.output_vat IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.output_vat AS numeric) * 100, 0) AS bigint) END; NEW.input_vat_minor = CASE WHEN NEW.input_vat IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.input_vat AS numeric) * 100, 0) AS bigint) END; NEW.vat_to_pay_minor = CASE WHEN NEW.vat_to_pay IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.vat_to_pay AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'journal_entries' THEN NEW.debit_minor = CASE WHEN NEW.debit IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.debit AS numeric) * 100, 0) AS bigint) END; NEW.credit_minor = CASE WHEN NEW.credit IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.credit AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'owner_transactions' THEN NEW.amount_minor = CASE WHEN NEW.amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; ELSIF TG_TABLE_NAME = 'audit_events' THEN NEW.amount_minor = CASE WHEN NEW.amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; END IF; RETURN NEW; END; $$");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS products_money_shadow_sync ON products");
    jdbcTemplate.execute("CREATE TRIGGER products_money_shadow_sync BEFORE INSERT OR UPDATE ON products FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS customer_orders_money_shadow_sync ON customer_orders");
    jdbcTemplate.execute("CREATE TRIGGER customer_orders_money_shadow_sync BEFORE INSERT OR UPDATE ON customer_orders FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS invoice_payments_money_shadow_sync ON invoice_payments");
    jdbcTemplate.execute("CREATE TRIGGER invoice_payments_money_shadow_sync BEFORE INSERT OR UPDATE ON invoice_payments FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS supplier_invoices_money_shadow_sync ON supplier_invoices");
    jdbcTemplate.execute("CREATE TRIGGER supplier_invoices_money_shadow_sync BEFORE INSERT OR UPDATE ON supplier_invoices FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS expenses_money_shadow_sync ON expenses");
    jdbcTemplate.execute("CREATE TRIGGER expenses_money_shadow_sync BEFORE INSERT OR UPDATE ON expenses FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS card_purchases_money_shadow_sync ON card_purchases");
    jdbcTemplate.execute("CREATE TRIGGER card_purchases_money_shadow_sync BEFORE INSERT OR UPDATE ON card_purchases FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS stripe_payouts_money_shadow_sync ON stripe_payouts");
    jdbcTemplate.execute("CREATE TRIGGER stripe_payouts_money_shadow_sync BEFORE INSERT OR UPDATE ON stripe_payouts FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS bank_reconciliation_entries_money_shadow_sync ON bank_reconciliation_entries");
    jdbcTemplate.execute("CREATE TRIGGER bank_reconciliation_entries_money_shadow_sync BEFORE INSERT OR UPDATE ON bank_reconciliation_entries FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS vat_filings_money_shadow_sync ON vat_filings");
    jdbcTemplate.execute("CREATE TRIGGER vat_filings_money_shadow_sync BEFORE INSERT OR UPDATE ON vat_filings FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS journal_entries_money_shadow_sync ON journal_entries");
    jdbcTemplate.execute("CREATE TRIGGER journal_entries_money_shadow_sync BEFORE INSERT OR UPDATE ON journal_entries FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS owner_transactions_money_shadow_sync ON owner_transactions");
    jdbcTemplate.execute("CREATE TRIGGER owner_transactions_money_shadow_sync BEFORE INSERT OR UPDATE ON owner_transactions FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS audit_events_money_shadow_sync ON audit_events");
    jdbcTemplate.execute("CREATE TRIGGER audit_events_money_shadow_sync BEFORE INSERT OR UPDATE ON audit_events FOR EACH ROW EXECUTE FUNCTION sync_money_shadow_fields()");
    jdbcTemplate.execute("CREATE OR REPLACE FUNCTION sync_supplier_payment_shadow_fields() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN NEW.amount_minor = CASE WHEN NEW.amount IS NULL THEN NULL ELSE CAST(ROUND(CAST(NEW.amount AS numeric) * 100, 0) AS bigint) END; NEW.currency_code = 'SEK'; RETURN NEW; END; $$");
    jdbcTemplate.execute("DROP TRIGGER IF EXISTS supplier_invoice_payments_money_shadow_sync ON supplier_invoice_payments");
    jdbcTemplate.execute("CREATE TRIGGER supplier_invoice_payments_money_shadow_sync BEFORE INSERT OR UPDATE ON supplier_invoice_payments FOR EACH ROW EXECUTE FUNCTION sync_supplier_payment_shadow_fields()");
  }
}
